<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Supreeth-PC" name="cucumber.Runner.TestRunner" tests="6" failures="0" timestamp="26 Oct 2021 12:09:33 GMT" time="23.479" errors="1">
  <testcase name="feature" time="9.361" classname="cucumber.Runner.TestRunner"/>
  <testcase name="feature" time="2.828" classname="cucumber.Runner.TestRunner"/>
  <testcase name="feature" time="3.270" classname="cucumber.Runner.TestRunner">
    <error type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: Value is invalid expected [true] but found [false]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Value is invalid expected [true] but found [false]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.AssertionError: Value is invalid expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at utilities.GenericUtility.assertResultisPositive(GenericUtility.java:67)
	at stepDefinitions.SearchUserStepDefinition.validate_that_the_response_is_valid_and_and_is_searched_successfully(SearchUserStepDefinition.java:27)
	at âœ½.Then Validate that the response is valid and "18" and "tobias.funke@reqres.in$Tobias$Funke$https://reqres.in/img/faces/9-image.jpg$https://reqres.in/#support-heading$To keep ReqRes free, contributions towards server costs are appreciated!" is searched successfully(SearchUser.feature:8)
]]>
    </error>
  </testcase> <!-- feature -->
  <testcase name="feature" time="2.319" classname="cucumber.Runner.TestRunner"/>
  <testcase name="feature" time="3.777" classname="cucumber.Runner.TestRunner"/>
  <testcase name="feature" time="1.924" classname="cucumber.Runner.TestRunner"/>
</testsuite> <!-- cucumber.Runner.TestRunner -->
